//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecureBank.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class OccupationDetail
    {
        [DataMember]
        public int OID { get; set; }
        [DataMember]
        public Nullable<int> CID { get; set; }
        [DataMember]
        public string Occupationtype { get; set; }
        [DataMember]
        public string SourceofIncome { get; set; }
        [DataMember]
        public Nullable<double> GrossannualIncome { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
