//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecureBank.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class PermanentAddress
    {
        [DataMember]
        public int PID { get; set; }
        [DataMember]
        public Nullable<int> CID { get; set; }
        [DataMember]
        public string PAddressLine1 { get; set; }
        [DataMember]
        public string PAddressLine2 { get; set; }
        [DataMember]
        public string PLandmark { get; set; }
        [DataMember]
        public string PState { get; set; }
        [DataMember]
        public string PCity { get; set; }
        [DataMember]
        public string PPincode { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
